service: samplesls

provider:
  name: aws
  runtime: go1.x

  apiKeys:
    - statusapi-${opt:stage, self:provider.stage}
  usagePlan:
    throttle:
      burstLimit: 20
      rateLimit: 10
package:
 exclude:
   - ./**
 include:
   - ./bin/**

   
functions:
  sample:
    handler: bin/sample
    events:
      - http:
          path: /sample
          method: get
          private: true
    vpc:
      securityGroupIds:
        - sg-37540a47
      subnetIds:
        - subnet-df5a15a6
        - subnet-33caa378
